typecheck:tapioca seems to need :compile before
* Otherwise:
rake aborted!
TypeError: superclass mismatch for class Prism::ParseResult (Prism::Result is given but was Object) (TypeError)

        kernel_class.send(:no_warning_require, name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
/home/runner/work/prism/prism/lib/prism.rb:82:in `<top (required)>'
/home/runner/work/prism/prism/vendor/bundle/ruby/3.3.0/gems/spoom-1.3.2/lib/spoom/deadcode.rb:5:in `<top (required)>'
/home/runner/work/prism/prism/vendor/bundle/ruby/3.3.0/gems/spoom-1.3.2/lib/spoom.rb:18:in `<top (required)>'
/home/runner/work/prism/prism/vendor/bundle/ruby/3.3.0/gems/tapioca-0.13.3/lib/tapioca/internal.rb:22:in `<top (required)>'
/home/runner/work/prism/prism/rakelib/typecheck.rake:19:in `block (2 levels) in <top (required)>'
/home/runner/work/prism/prism/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.1/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.3.1/x64/bin/bundle:25:in `<main>'
Tasks: TOP => typecheck:tapioca