Fix `Source.offsets` with `freeze: true`
We still need to do it eagerly when the result will be frozen, same
as for locations.

Fixes the following error for the added test:
> FrozenError: can't modify frozen Prism::ASCIISource: #<Prism::ASCIISource:0x00007ff9d57586f0 @source="1 + 2", @start_line=1, @offsets="\x00\x00\x00\x00">