Raise error from bin/parse for missing source code and file
Previously, if you called `bin/parse` without `-e` or a file, you would
get the following confusing error:

```
$ bin/parse
open: No such file or directory
bin/parse:20:in `<main>': undefined method `value' for nil:NilClass (NoMethodError)

value = result.value
              ^^^^^^
```

Now you get an `ArgumentError`:

```
$ bin/parse
open: No such file or directory
bin/parse:17:in `<main>': There was nothing to parse. You must pass source code with `-e` or a Ruby file. (ArgumentError)
```