Move PRISM_NODISCARD to the correct position, again
Followup to https://github.com/ruby/prism/commit/ba16ae22561179998e4208e4c37262b47f693c11

I can't run rake `cargo:test`:
```
$ cargo build
   Compiling ruby-prism-sys v1.9.0 (ruby-prism/rust/ruby-prism-sys)
   Compiling ruby-prism v1.9.0 (ruby-prism/rust/ruby-prism)
warning: ruby-prism-sys@1.9.0: In file included from ruby-prism/rust/ruby-prism-sys/vendor/prism-1.9.0/include/prism/ast.h:22,
warning: ruby-prism-sys@1.9.0:                  from ruby-prism/rust/ruby-prism-sys/vendor/prism-1.9.0/include/prism/internal/static_literals.h:6,
warning: ruby-prism-sys@1.9.0:                  from ruby-prism/rust/ruby-prism-sys/vendor/prism-1.9.0/src/static_literals.c:1:
warning: ruby-prism-sys@1.9.0: ruby-prism/rust/ruby-prism-sys/vendor/prism-1.9.0/include/prism/arena.h:28:1: warning: 'nodiscard' attribute ignored [-Wattributes]
warning: ruby-prism-sys@1.9.0:    28 | PRISM_EXPORTED_FUNCTION PRISM_NODISCARD pm_arena_t * pm_arena_new(void);
warning: ruby-prism-sys@1.9.0:       | ^~~~~~~~~~~~~~~~~~~~~~~
warning: ruby-prism-sys@1.9.0: ruby-prism/rust/ruby-prism-sys/vendor/prism-1.9.0/include/prism/arena.h:28:41: error: expected identifier or '(' before 'pm_arena_t'
warning: ruby-prism-sys@1.9.0:    28 | PRISM_EXPORTED_FUNCTION PRISM_NODISCARD pm_arena_t * pm_arena_new(void);
warning: ruby-prism-sys@1.9.0:       |                                         ^~~~~~~~~~
error: failed to run custom build command for `ruby-prism-sys v1.9.0 (ruby-prism/rust/ruby-prism-sys)`
```

It expands to `__attribute__((__visibility__("default"))) extern [[nodiscard]] pm_arena_t * pm_arena_new(void);`, which is not valid in that order.