Fix Java class ParsingOptions.Scope and make its constructors public
This fixes the issue with using the Scope class outside the Prism gem. Otherwise building fails with the following error:

```
...src/main/java/org/truffleruby/parser/YARPTranslatorDriver.java:89: error: constructor Scope in class Scope cannot be applied to given types;
    private static final ParsingOptions.Scope EMPTY_SCOPE = new ParsingOptions.Scope(EMPTY_BYTE_ARRAY_ARRAY,
                                                            ^
  required: byte[][],Forwarding[]
  found:    byte[][],Forwarding[]
  reason: Scope(byte[][],Forwarding[]) is not public in Scope; cannot be accessed from outside package
```