Because truffleruby now uses prism itself for its ripper implementation, the templates need to be created beforehand.
So, move the ripper require inside the tasks itself, after which the templates have been created.

Example failure: https://github.com/ruby/prism/actions/runs/24358711087/job/71132405299

```
LoadError: cannot load such file -- /home/runner/work/prism/prism/lib/prism/node (LoadError)
/home/runner/work/prism/prism/lib/prism.rb:127:in '<top (required)>'
/home/runner/work/prism/prism/rakelib/lex.rake:4:in '<top (required)>'
/home/runner/work/prism/prism/vendor/bundle/truffleruby/34.0.0.1/gems/rake-13.3.1/exe/rake:27:in '<top (required)>'
/home/runner/.rubies/truffleruby-34.0.0/bin/bundle:25:in '<main>'
(See full trace by running task with --trace)
```

`lex.rake:4` is `require "ripper"`