Avoid warning for pm_token_buffer_t initialization
* This was causing this error on macOS Mojave:
  src/prism.c:8216:48: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
            pm_token_buffer_t token_buffer = { 0 };
                                               ^